password = "badm554"
SALES_DATABASE_URL = "mysql://badmstudent:badmstudent@badmstudent.cte4bvaqxbgn.us-east-2.rds.amazonaws.com:3306/sales"
NORTHWIND_DATABASE_URL = "mysql://badmstudent:badmstudent@badmstudent.cte4bvaqxbgn.us-east-2.rds.amazonaws.com:3306/northwind"